# Generated by Django 3.2.7 on 2021-09-19 08:18

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_education_patient_speciality_therapist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('recurring', django.contrib.postgres.fields.ranges.DateRangeField(verbose_name='Recurring')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_configs', to='users.therapist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_availabilities', to='scheduling.availabilityconfig')),
            ],
            options={
                'verbose_name_plural': 'Custom Availabilities',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='MONDAY', max_length=10, verbose_name='Day')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='scheduling.availabilityconfig')),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Appointment date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Appointment time')),
                ('duration', models.IntegerField(default=15, null=True, verbose_name='Appointment duration in minutes')),
                ('appointment_type', models.CharField(choices=[('OT', 'Occupational'), ('PT', 'Physical'), ('ST', 'Speech')], max_length=50, verbose_name='Appointment type')),
                ('status', models.CharField(choices=[('PENDING DETAILS', 'Pending Details'), ('PENDING PAYMENT', 'Pending Payment'), ('PENDING APPROVAL', 'Pending Approval'), ('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING PAYMENT', max_length=50, verbose_name='Appointment status')),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Therapist fee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='users.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_appointments', to='users.therapist')),
            ],
            options={
                'unique_together': {('date', 'time', 'patient_id', 'therapist_id')},
            },
        ),
    ]
